services:

  # listens to mqtt packets and saves to database
  meshtastic-mqtt:
    container_name: meshtastic-mqtt
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./Dockerfile
    command: /app/docker/mqtt.sh
    environment:
      DATABASE_URL: "mysql://root:password@database:3306/meshtastic-map?connection_limit=100"
      MQTT_OPTS: "--mqtt-broker-url 65.109.32.218:1883 --mqtt-username mesh --mqtt-password tastic --mqtt-topic msh/# "
    networks:
      - mesh-map

  # runs the web map ui
  meshtastic-map:
    container_name: meshtastic-map
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./Dockerfile
    command: /app/docker/map.sh
    environment:
      DATABASE_URL: "mysql://root:password@database:3306/meshtastic-map?connection_limit=100"
      MAP_OPTS: "" # add any custom index.js options here
    networks:
      - mesh-map
      - rproxy-manager_default

  # runs the database to store everything from mqtt
  database:
    container_name: database
    image: bitnami/mariadb
    environment:
      MARIADB_DATABASE: "meshtastic-map"
      MARIADB_ROOT_PASSWORD: "password"
    volumes:
      - database_data:/bitnami/mariadb
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
      start_interval: 5s
    networks:
      - mesh-map

volumes:
  database_data:

networks:
  rproxy-manager_default:
    external: true
    name: rproxy-manager_default
  mesh-map:
    name: mesh-map
